import type { ScanReport } from "@/lib/scans/types";

export const exampleReport: ScanReport = {
  url: "https://example-app.invalid",
  startedAt: "2026-09-15T16:00:00.000Z",
  completedAt: "2026-09-15T16:04:00.000Z",
  plan: "free",
  mode: "http",
  pagesCrawled: [],
  holeCount: 6,
  blockerCount: 3,
  testBeforeCount: 2,
  notBlockingCount: 1,
  unverifiedCount: 1,
  passCount: 1,
  verdict: "PLUG_THESE_FIRST",
  verdictSummary: "Plug 3 AppHoles before putting this in front of buyers.",
  checked: ["Homepage", "Signup", "Pricing", "Mobile viewport", "Privacy", "Support"],
  couldNotVerify: ["Live card charge"],
  findings: [
    {
      id: "ex_1",
      category: "payment",
      title: "Checkout fails on mobile",
      observed: "Tapping Pay on a 390px viewport returns an error before a checkout session opens.",
      expected: "A customer on a phone should reach a functional checkout.",
      disposition: "FIX_BEFORE_SELLING",
      severity: "high",
      confidence: 0.96,
      url: "https://example-app.invalid/checkout",
      viewport: "390x844",
      browser: "example",
      evidence: [{ type: "note", label: "example", value: "Illustrated finding. Not from a live customer app." }],
      whyItMatters: "A mobile customer cannot complete a purchase.",
      recommendedPlug: "Fix the mobile payment handler and retest checkout on a 390px viewport.",
      retest: "Open /checkout at 390px and tap Pay.",
    },
    {
      id: "ex_2",
      category: "first_run",
      title: "New users land on an empty dashboard",
      observed: "A new account reaches /dashboard with no projects, no instruction, and no visible primary action.",
      expected: "The first useful action should be obvious after signup.",
      disposition: "FIX_BEFORE_SELLING",
      severity: "high",
      confidence: 0.9,
      url: "https://example-app.invalid/dashboard",
      browser: "example",
      evidence: [{ type: "note", label: "example", value: "Illustrated finding." }],
      whyItMatters: "A first-time user can register and still fail to experience the product.",
      recommendedPlug: "Route empty accounts to the first useful action or give the empty state a strong CTA.",
      retest: "Create a new account and stop on the first screen after verification.",
    },
    {
      id: "ex_3",
      category: "signup_login",
      title: "Password reset link is broken",
      observed: "The reset URL returns an expired or 404 page immediately.",
      expected: "Recovery should return the user to a working login.",
      disposition: "FIX_BEFORE_SELLING",
      severity: "high",
      confidence: 0.91,
      url: "https://example-app.invalid/reset",
      browser: "example",
      evidence: [{ type: "note", label: "example", value: "Illustrated finding." }],
      whyItMatters: "If login fails once, recovery is the only path back. Broken reset loses the customer.",
      recommendedPlug: "Fix token validation and the reset landing page, then retest the full email link.",
      retest: "Request a reset and open the link in a fresh browser.",
    },
    {
      id: "ex_4",
      category: "purchase_moment",
      title: "No clear paid action exists",
      observed: "The product is usable, but nothing asks the user to buy, upgrade, or start a trial.",
      expected: "If you intend to charge, users should encounter a buying decision.",
      disposition: "TEST_BEFORE_BUILDING",
      severity: "medium",
      confidence: 0.8,
      browser: "example",
      evidence: [{ type: "note", label: "example", value: "Illustrated finding." }],
      whyItMatters: "Building more features will not invent a purchase moment.",
      recommendedPlug: "Put one honest paid action in the path. Then talk to buyers before adding plan tiers.",
      retest: "Walk a new user from value to a visible paywall or upgrade CTA.",
    },
    {
      id: "ex_5",
      category: "pricing",
      title: "Pricing contradicts the product",
      observed: "The landing page says unlimited, while checkout shows a hard monthly cap.",
      expected: "Public promises and checkout should match.",
      disposition: "TEST_BEFORE_BUILDING",
      severity: "medium",
      confidence: 0.77,
      browser: "example",
      evidence: [{ type: "note", label: "example", value: "Illustrated finding." }],
      whyItMatters: "Contradiction creates distrust. Confirm the intended offer before rebuilding billing UI.",
      recommendedPlug: "Align landing copy with the actual entitlement, then verify checkout.",
      retest: "Compare landing, pricing, and checkout side by side.",
    },
    {
      id: "ex_6",
      category: "privacy",
      title: "Privacy language is incomplete",
      observed: "A privacy link exists, but it is a one-line placeholder.",
      expected: "If you collect accounts, say what you store.",
      disposition: "NOT_BLOCKING_A_SALE",
      severity: "low",
      confidence: 0.7,
      browser: "example",
      evidence: [{ type: "note", label: "example", value: "Illustrated finding." }],
      whyItMatters: "Real gap. Not a rational reason to postpone the first customer conversation.",
      recommendedPlug: "Publish a short accurate privacy page. This is not legal advice.",
      retest: "Open the footer privacy link.",
    },
    {
      id: "ex_7",
      category: "core_functionality",
      title: "Core workflow works",
      observed: "The primary happy path completed without a crash in this example.",
      expected: "The core job should complete.",
      disposition: "PASS",
      severity: "info",
      confidence: 0.84,
      browser: "example",
      evidence: [{ type: "note", label: "example", value: "Illustrated finding." }],
      whyItMatters: "Passes matter. AppHole is not trying to maximize issue count.",
      recommendedPlug: "No plug required.",
      retest: "Repeat the core workflow on desktop and mobile.",
    },
    {
      id: "ex_8",
      category: "browser",
      title: "Runtime browsers beyond this HTTP check were not launched",
      observed: "This example report did not drive Chromium, WebKit, or Firefox.",
      expected: "Console errors, screenshots, and tap-target failures need a real browser.",
      disposition: "COULDNT_VERIFY",
      severity: "info",
      confidence: 1,
      browser: "example",
      evidence: [{ type: "note", label: "example", value: "Illustrated finding." }],
      whyItMatters: "Inventing console errors would be dishonest. AppHole prefers couldn't verify over theater.",
      recommendedPlug: "Run a local or Pro Playwright pass to capture console, network failures, and mobile screenshots.",
      retest: "Re-run with a browser worker enabled.",
    },
  ],
};
